apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service

spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    # - nodePort #not available of this service type.
    - port: 5432
      targetPort: 5432