apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service

spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    # - nodePort #not available of this service type.
    - port: 6379
      targetPort: 6379