apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service

spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    # - nodePort #not available of this service type.
    - port: 5000
      targetPort: 5000

# --- #multiple files can be used in one file in one file.